project:
  type: website
  output-dir: docs

website:
  title: "Tselmen Anuurad"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



